import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '@/components/Header';
import { WorkspaceViewProvider } from "@/contexts/WorkspaceViewContext";
import { SnackbarProvider } from "@/providers/SnackbarProvider";

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });
// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

export const metadata: Metadata = {
  title: "Geckode",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased min-h-screen flex flex-col">
        <WorkspaceViewProvider>
          <Header />
          <main
            className="flex-1 flex flex-col bg-gray-100 dark:bg-dark-secondary"
            id="app"
          >
            <SnackbarProvider>{children}</SnackbarProvider>
          </main>
        </WorkspaceViewProvider>
      </body>
    </html>
  );
}
