import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SnackbarProvider } from "@/providers/SnackbarProvider";

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });
// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

export const metadata: Metadata = {
  title: "Geckode",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  headerContent,
}: Readonly<{
  children: React.ReactNode;
  headerContent: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased min-h-screen flex flex-col">
        <header className="bg-primary-green flex items-center h-12 p-4">
          <h1 className="text-shadow-sm text-white text-2xl font-bold">
            Geckode
          </h1>
          <div className="ml-auto">{headerContent}</div>
        </header>
        <main
          className="flex-1 flex flex-col bg-gray-100 dark:bg-dark-secondary"
          id="app"
        >
          <SnackbarProvider>{children}</SnackbarProvider>
        </main>
      </body>
    </html>
  );
}
