import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });
// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

export const metadata: Metadata = {
  title: 'Geckode',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <header className="bg-primary-green flex items-center h-[4rem]">
          <h1 className="text-shadow-sm text-white pl-4 text-3xl">Geckode</h1>
        </header>
        <main className="h-[calc(100% - 4rem)]" id="app">
          {children}
        </main>
      </body>
    </html>
  );
}
