# Generated by Django 5.2.7 on 2025-10-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organizationmember_joined_at_and_more'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='shared_organizations',
            field=models.ManyToManyField(blank=True, related_name='projects', to='organizations.organization'),
        ),
    ]
