# Generated by Django 5.2.7 on 2025-10-16 04:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_shared_organizations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='forked_by',
            field=models.ManyToManyField(blank=True, related_name='forked_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
