# Generated by Django 5.2.7 on 2025-10-26 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organization_project_containment_and_more'),
        ('projects', '0003_project_forked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='shared_users',
            new_name='collaborators',
        ),
        migrations.RemoveField(
            model_name='project',
            name='shared_organizations',
        ),
        migrations.AlterField(
            model_name='project',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.projectgroup'),
        ),
        migrations.AlterField(
            model_name='projectcollaborator',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_collaborators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectcollaborator',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_collaborators', to='projects.project'),
        ),
        migrations.CreateModel(
            name='OrganizationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'Can view'), ('edit', 'Can modify code'), ('invite', 'Can invite and code'), ('admin', 'Can change project details')], max_length=10)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_projects', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_projects', to='projects.project')),
            ],
            options={
                'unique_together': {('organization', 'project')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='organizations',
            field=models.ManyToManyField(related_name='organizations', through='projects.OrganizationProject', to='organizations.organization'),
        ),
    ]
