# Generated by Django 5.2.7 on 2025-10-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_organization_is_public'),
        ('projects', '0004_rename_shared_users_project_collaborators_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationproject',
            name='permission',
            field=models.CharField(choices=[('view', 'Can view'), ('code', 'Can modify code'), ('invite', 'Can invite and code'), ('admin', 'Can change project details')], max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='organizations',
            field=models.ManyToManyField(related_name='projects', through='projects.OrganizationProject', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='projectcollaborator',
            name='permission',
            field=models.CharField(choices=[('view', 'Can view'), ('code', 'Can modify code'), ('invite', 'Can invite and code'), ('admin', 'Can change project details')], max_length=10),
        ),
    ]
