# Generated by Django 5.2.7 on 2025-11-01 17:29

import projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_organizationproject_permission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.project_thumbnail_path),
        ),
    ]
