# Generated by Django 5.2.7 on 2025-11-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='game_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
