# Generated by Django 5.2.7 on 2025-11-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_game_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sprites',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
