# Generated by Django 5.2.7 on 2025-11-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_sprites'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='blocks_binary',
            field=models.BinaryField(blank=True),
        ),
    ]
