# Generated by Django 5.2.7 on 2025-11-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_blocks_binary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='blocks_binary',
            field=models.BinaryField(blank=True, default=b''),
        ),
    ]
