# Generated by Django 5.2.7 on 2025-11-26 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_projectsnapshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectsnapshot',
            old_name='events',
            new_name='update',
        ),
        migrations.RemoveField(
            model_name='projectsnapshot',
            name='blocks',
        ),
    ]
