# Generated by Django 5.2.7 on 2026-02-11 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_sprite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sprite',
            new_name='Texture',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='sprites',
            new_name='textures',
        ),
        migrations.AlterUniqueTogether(
            name='texture',
            unique_together={('project', 'name')},
        ),
    ]
