# Generated by Django 5.2.7 on 2026-02-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_rename_sprite_texture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texture',
            name='texture',
            field=models.CharField(),
        ),
    ]
