# Generated by Django 5.2.7 on 2026-02-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_alter_texture_texture'),
    ]

    operations = [
        migrations.AddField(
            model_name='texture',
            name='texture_type',
            field=models.CharField(choices=[('textures', 'used for textures'), ('tiles', 'used for tiles')], default='textures'),
        ),
        migrations.AlterField(
            model_name='texture',
            name='texture',
            field=models.CharField(null=True),
        ),
    ]
