# Generated by Django 5.2.7 on 2026-02-12 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_texture_texture_type_alter_texture_texture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='textures',
            new_name='assets',
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset', models.CharField(null=True)),
                ('asset_type', models.CharField(choices=[('assets', 'used for assets'), ('tiles', 'used for tiles')], default='assets')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.DeleteModel(
            name='Texture',
        ),
    ]
