# Generated by Django 5.2.7 on 2026-02-12 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_rename_textures_project_assets_asset_delete_texture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='assets',
            new_name='sprites',
        ),
    ]
