# Generated by Django 5.2.7 on 2026-02-19 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_rename_assets_project_sprites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('textures', 'used for textures'), ('tiles', 'used for tiles')], default='textures'),
        ),
    ]
