# Generated by Django 5.2.7 on 2026-03-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_asset_asset_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='blocks',
        ),
        migrations.RemoveField(
            model_name='project',
            name='game_state',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sprites',
        ),
        migrations.AddField(
            model_name='project',
            name='yjs_blob',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
