# Generated by Django 5.2.7 on 2026-02-27 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_asset_asset_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpritePhysics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pushes_objects', models.BooleanField()),
                ('pushable', models.BooleanField()),
                ('collides_with_walls', models.BooleanField()),
                ('is_solid', models.BooleanField()),
                ('gravity_y', models.FloatField()),
                ('bounce', models.FloatField()),
                ('drag', models.FloatField()),
                ('collide_world_bounds', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SpriteWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprite_id', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprite_workspaces', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'sprite_id')},
            },
        ),
        migrations.CreateModel(
            name='SpriteInstance',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('texture_name', models.CharField(max_length=200)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('visible', models.BooleanField()),
                ('scale_x', models.FloatField()),
                ('scale_y', models.FloatField()),
                ('direction', models.FloatField()),
                ('snap_to_grid', models.BooleanField()),
                ('physics', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sprite', serialize=False, to='projects.spritephysics')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprites', to='projects.spriteworkspace')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_id', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('collapsed', models.BooleanField(blank=True, null=True)),
                ('deletable', models.BooleanField(blank=True, null=True)),
                ('movable', models.BooleanField(blank=True, null=True)),
                ('editable', models.BooleanField(blank=True, null=True)),
                ('enabled', models.BooleanField(blank=True, null=True)),
                ('disabled_reasons', models.JSONField(blank=True, null=True)),
                ('inline', models.BooleanField(blank=True, null=True)),
                ('data', models.CharField(max_length=200)),
                ('extra_state', models.JSONField(blank=True, null=True)),
                ('icons', models.JSONField(blank=True, null=True)),
                ('fields', models.JSONField(blank=True, null=True)),
                ('is_shadow', models.BooleanField(blank=True, null=True)),
                ('parent_id', models.CharField(blank=True, max_length=50, null=True)),
                ('input_name', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='projects.spriteworkspace')),
            ],
            options={
                'unique_together': {('workspace', 'block_id')},
            },
        ),
    ]
