# Generated by Django 5.2.7 on 2026-03-10 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_projectsharelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_share_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_projects', to='projects.projectsharelink'),
        ),
    ]
