# Generated by Django 5.2.7 on 2025-10-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_organizationpermission_invited_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationinvitation',
            name='permission',
            field=models.CharField(choices=[('view', 'Can view projects'), ('contribute', 'Can contribute projects'), ('invite', 'Can invite members'), ('manage', 'Can remove members'), ('admin', 'Can modify details')], default='view', max_length=10),
            preserve_default=False,
        ),
    ]
