# Generated by Django 5.2.7 on 2025-10-26 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organizationmember_joined_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='project_containment',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='organizationinvitation',
            name='invitee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitee_organization_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationinvitation',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inviter_organization_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='invited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inviter_organization_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_members', to='organizations.organization'),
        ),
    ]
