# Generated by Django 5.2.7 on 2025-10-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_organization_project_containment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_public',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
