# Generated by Django 5.2.7 on 2025-10-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_organization_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='default_member_permission',
            field=models.CharField(choices=[('view', 'Can view projects'), ('contribute', 'Can contribute projects'), ('invite', 'Can invite members'), ('manage', 'Can remove members'), ('admin', 'Can modify details')], default='view', max_length=10),
        ),
    ]
