# Generated by Django 5.2.7 on 2025-11-01 17:27

import organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_organizationbannedmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=organizations.models.org_thumbnail_path),
        ),
    ]
